on: [push, pull_request]

name: Check Confidence

jobs: 
  check: 
    name: Check
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with: 
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check for lib
        run: cd confidence && cargo check

      - name: Run cargo check for demo
        run: cd demo && cargo check

  test: 
    name: Test Suite
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with: 
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        run: cd confidence && cargo test